In [1]:
import os
import sys
sys.path.append(os.pardir)

import numpy as np
from common.functions import cross_entropy_error
from common.functions import softmax
from common.gradient import numerical_gradient

In [2]:
class SimpleNet:
    def __init__(self):
        self.W = np.random.randn(2, 3)
        
    def predict(self, x):
        return np.dot(x, self.W)
    
    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)
        return loss

In [3]:
net = SimpleNet()
print(net.W)

[[-2.97998201  2.57673981  0.3698523 ]
 [-0.5361443   0.0506418  -0.20727411]]


In [4]:
x = np.array([0.6, 0.9])
p = net.predict(x)
print(p, np.argmax(p))

[-2.27051908  1.59162151  0.03536468] 1


In [5]:
t = np.array([0, 0, 1])
net.loss(x, t)

1.7648521476784165

In [6]:
def f(W):
    return net.loss(x, t)

dW = numerical_gradient(f, net.W)
print(dW)

[[ 0.01023888  0.48703363 -0.49727251]
 [ 0.01535833  0.73055044 -0.74590877]]
